### ISSUE TITLE
can't push something that had been deleted on the peer

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#86]
hello, Semacquire!
```#   0x4b12ef    sync.runtime_Semacquire+0x2f                                                                    /usr/lib/go-1.7/src/runtime/sema.go:47
#   0x591b3f    sync.(*Mutex).Lock+0xcf                                                                     /usr/lib/go-1.7/src/sync/mutex.go:85
#   0x45e292    main.(*InMemoryState).deleteFilesystem.func1+0x32                                                       /go/src/github.com/datamesh-io/datamesh/cmd/datamesh-server/pkg/main/controller.go:75
#   0x402d9a    main.(*InMemoryState).deleteFilesystem+0xfa                                                         /go/src/github.com/datamesh-io/datamesh/cmd/datamesh-server/pkg/main/controller.go:78
#   0x40757d    main.(*InMemoryState).initFilesystemMachine+0x36d                                                       /go/src/github.com/datamesh-io/datamesh/cmd/datamesh-server/pkg/main/controller.go:506
#   0x42c72f    main.(*DatameshRPC).registerFilesystemBecomeMaster+0x37f                                                    /go/src/github.com/datamesh-io/datamesh/cmd/datamesh-server/pkg/main/rpc.go:528
#   0x42d4dc    main.(*DatameshRPC).RegisterFilesystem+0x1ec                                                            /go/src/github.com/datamesh-io/datamesh/cmd/datamesh-server/pkg/main/rpc.go:630
#   0x4ce8eb    runtime.call64+0x4
```
(edited)

[10:58] 
a-ha! it’s a deletion re-entrancy bug??

[10:58] 
oh, I tried to push a filesystem that had been previously deleted!

[10:58] 
lol

[10:58] 
i.e.

[10:59] 
ALICE -> creates filesystem
ALICE -> pushes filesystem to BOB
BOB -> deletes filesystem
ALICE -> pushes filesystem to BOB again

[10:59] 
<hang>

[10:59] 
what should happen?

[10:59] 
bob should probably allow the filesystem to come _out_ of the deletion list

[11:00] 
for now at least, it could return an error

**Comment by alaric-datamesh** [comment]
This should be fixed by https://github.com/dotmesh-io/dotmesh/issues/186

**Comment by lukemarsden** [comment]
well, #186 might help with the locking issues, but the fundamental issue remains that we need to support re-pushing previously deleted filesystems without id collisions

**Comment by lukemarsden** [comment]
https://github.com/dotmesh-io/dotmesh/commit/8d601261db43d848327806cb9708dd44f97f3475 and friends should fix the double-acquire, anyway
